variable "filename" {
    default = "C:\\Users\\ShraddhaSuryawanshi\\OneDrive - NTT Data Payment Services Limited\\Shraddha Suryawanshi\\MY_NOTES\\Self\\Terraform\\Basic\\Files\\terrafrom_automated.txt"
}

variable "content" {
    default = "Generated by terraform automatically...!!"
}

variable "content_map" {    
    type = map 
    default = {
        "content_1" = "My content is certaed in  1"
        "content_2" = "My content is certaed in  2"
    }
}

variable "file_list" {
  type = list
  default = ["C:\\Users\\ShraddhaSuryawanshi\\OneDrive - NTT Data Payment Services Limited\\Shraddha Suryawanshi\\MY_NOTES\\Self\\Terraform\\Basic\\Files\\file_1.txt", "C:\\Users\\ShraddhaSuryawanshi\\OneDrive - NTT Data Payment Services Limited\\Shraddha Suryawanshi\\MY_NOTES\\Self\\Terraform\\Basic\\Files\\file_2.txt"]
}